# Generated by Django 5.0 on 2024-01-03 18:16

import Technoagaaz.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnoagaazTeam',
            fields=[
                ('teamID', Technoagaaz.models.CustomAutoField(editable=False, primary_key=True, serialize=False)),
                ('teamName', models.CharField(max_length=100)),
                ('leaderName', models.CharField(max_length=100)),
                ('emailID', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phoneNO', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be between 10 and 15 digits.', regex='^\\d{10,15}$')])),
                ('event', models.CharField(blank=True, max_length=100, null=True)),
                ('game', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('order_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_signature', models.CharField(blank=True, max_length=100, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_TechnoagaazTeams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TechnoagaazTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='Technoagaaz.technoagaazteam')),
            ],
            options={
                'unique_together': {('team', 'name')},
            },
        ),
    ]
