# Generated by Django 5.0 on 2023-12-25 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Spoorti', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='users',
            new_name='user',
        ),
    ]
