# Generated by Django 5.0 on 2023-12-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spoorti', '0004_alter_team_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='order_ID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='payment_ID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='payment_signature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
